// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	llmdinferenceschedulerapixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	versioned "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned"
	internalinterfaces "github.com/llm-d/llm-d-inference-scheduler/client-go/informers/externalversions/internalinterfaces"
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/listers/apix/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceObjectiveInformer provides access to a shared informer and lister for
// InferenceObjectives.
type InferenceObjectiveInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apixv1alpha2.InferenceObjectiveLister
}

type inferenceObjectiveInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInferenceObjectiveInformer constructs a new informer for InferenceObjective type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceObjectiveInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInferenceObjectiveInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInferenceObjectiveInformer constructs a new informer for InferenceObjective type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInferenceObjectiveInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceObjectives(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceObjectives(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceObjectives(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceObjectives(namespace).Watch(ctx, options)
			},
		}, client),
		&llmdinferenceschedulerapixv1alpha2.InferenceObjective{},
		resyncPeriod,
		indexers,
	)
}

func (f *inferenceObjectiveInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInferenceObjectiveInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *inferenceObjectiveInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&llmdinferenceschedulerapixv1alpha2.InferenceObjective{}, f.defaultInformer)
}

func (f *inferenceObjectiveInformer) Lister() apixv1alpha2.InferenceObjectiveLister {
	return apixv1alpha2.NewInferenceObjectiveLister(f.Informer().GetIndexer())
}
