// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	llmdinferenceschedulerapixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	versioned "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned"
	internalinterfaces "github.com/llm-d/llm-d-inference-scheduler/client-go/informers/externalversions/internalinterfaces"
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/listers/apix/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceModelRewriteInformer provides access to a shared informer and lister for
// InferenceModelRewrites.
type InferenceModelRewriteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apixv1alpha2.InferenceModelRewriteLister
}

type inferenceModelRewriteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInferenceModelRewriteInformer constructs a new informer for InferenceModelRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceModelRewriteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInferenceModelRewriteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInferenceModelRewriteInformer constructs a new informer for InferenceModelRewrite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInferenceModelRewriteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XInferenceV1alpha2().InferenceModelRewrites(namespace).Watch(ctx, options)
			},
		}, client),
		&llmdinferenceschedulerapixv1alpha2.InferenceModelRewrite{},
		resyncPeriod,
		indexers,
	)
}

func (f *inferenceModelRewriteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInferenceModelRewriteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *inferenceModelRewriteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&llmdinferenceschedulerapixv1alpha2.InferenceModelRewrite{}, f.defaultInformer)
}

func (f *inferenceModelRewriteInformer) Lister() apixv1alpha2.InferenceModelRewriteLister {
	return apixv1alpha2.NewInferenceModelRewriteLister(f.Informer().GetIndexer())
}
