// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	internalinterfaces "github.com/llm-d/llm-d-inference-scheduler/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// InferenceModelRewrites returns a InferenceModelRewriteInformer.
	InferenceModelRewrites() InferenceModelRewriteInformer
	// InferenceObjectives returns a InferenceObjectiveInformer.
	InferenceObjectives() InferenceObjectiveInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// InferenceModelRewrites returns a InferenceModelRewriteInformer.
func (v *version) InferenceModelRewrites() InferenceModelRewriteInformer {
	return &inferenceModelRewriteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// InferenceObjectives returns a InferenceObjectiveInformer.
func (v *version) InferenceObjectives() InferenceObjectiveInformer {
	return &inferenceObjectiveInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
