apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-sim-metrics
  labels:
    app: vllm-sim-metrics
spec:
  selector:
    matchLabels:
      app: ${POOL_NAME}
  podMetricsEndpoints:
  - port: sidecar-http
    interval: 15s
    path: /metrics
