// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// InferenceModelRewriteListerExpansion allows custom methods to be added to
// InferenceModelRewriteLister.
type InferenceModelRewriteListerExpansion interface{}

// InferenceModelRewriteNamespaceListerExpansion allows custom methods to be added to
// InferenceModelRewriteNamespaceLister.
type InferenceModelRewriteNamespaceListerExpansion interface{}

// InferenceObjectiveListerExpansion allows custom methods to be added to
// InferenceObjectiveLister.
type InferenceObjectiveListerExpansion interface{}

// InferenceObjectiveNamespaceListerExpansion allows custom methods to be added to
// InferenceObjectiveNamespaceLister.
type InferenceObjectiveNamespaceListerExpansion interface{}
