// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceModelRewriteLister helps list InferenceModelRewrites.
// All objects returned here must be treated as read-only.
type InferenceModelRewriteLister interface {
	// List lists all InferenceModelRewrites in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha2.InferenceModelRewrite, err error)
	// InferenceModelRewrites returns an object that can list and get InferenceModelRewrites.
	InferenceModelRewrites(namespace string) InferenceModelRewriteNamespaceLister
	InferenceModelRewriteListerExpansion
}

// inferenceModelRewriteLister implements the InferenceModelRewriteLister interface.
type inferenceModelRewriteLister struct {
	listers.ResourceIndexer[*apixv1alpha2.InferenceModelRewrite]
}

// NewInferenceModelRewriteLister returns a new InferenceModelRewriteLister.
func NewInferenceModelRewriteLister(indexer cache.Indexer) InferenceModelRewriteLister {
	return &inferenceModelRewriteLister{listers.New[*apixv1alpha2.InferenceModelRewrite](indexer, apixv1alpha2.Resource("inferencemodelrewrite"))}
}

// InferenceModelRewrites returns an object that can list and get InferenceModelRewrites.
func (s *inferenceModelRewriteLister) InferenceModelRewrites(namespace string) InferenceModelRewriteNamespaceLister {
	return inferenceModelRewriteNamespaceLister{listers.NewNamespaced[*apixv1alpha2.InferenceModelRewrite](s.ResourceIndexer, namespace)}
}

// InferenceModelRewriteNamespaceLister helps list and get InferenceModelRewrites.
// All objects returned here must be treated as read-only.
type InferenceModelRewriteNamespaceLister interface {
	// List lists all InferenceModelRewrites in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha2.InferenceModelRewrite, err error)
	// Get retrieves the InferenceModelRewrite from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apixv1alpha2.InferenceModelRewrite, error)
	InferenceModelRewriteNamespaceListerExpansion
}

// inferenceModelRewriteNamespaceLister implements the InferenceModelRewriteNamespaceLister
// interface.
type inferenceModelRewriteNamespaceLister struct {
	listers.ResourceIndexer[*apixv1alpha2.InferenceModelRewrite]
}
