version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

formatters:
  enable:
    - goimports
    - gofmt

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - fatcontext
    - ginkgolinter
    - goconst
    - gocritic
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilnil
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
    - unconvert
  settings:
    revive: # see https://github.com/mgechev/revive#available-rules for all options
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

issues:
  # do not limit the number of issues, ensure even identical are reported
  max-issues-per-linter: 0
  max-same-issues: 0
  # Note: 'new' setting is controlled via Makefile LINT_NEW_ONLY variable
  # Set to true to only check new code, false (default) to check all code
