# Ignore transient failures on gnu.org (it sometimes refuses connections)
exclude = [
  "^https://www.gnu.org/software/make/?$",
  "^https://www.envoyproxy.io/"
]

# Timeout in seconds
timeout = 20

# Retry failed links (helpful for flaky sites)
max_retries = 5
retry_wait_time = 2

# Accept non-200 status codes (429: rate limits)
accept = [200, 429]
