# Go build stage
FROM --platform=${BUILDPLATFORM} quay.io/projectquay/golang:1.25 AS go-builder

ARG TARGETOS
ARG TARGETARCH
ARG LDFLAGS="-s -w"

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Download dependencies - this layer is cached as long as go.mod/go.sum are unchanged
RUN go mod download

# Copy the go source
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN go mod download

# Build EPP
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="${LDFLAGS}" -o bin/epp cmd/epp/main.go

# Runtime stage
# Use ubi9-micro as a minimal base image
FROM registry.access.redhat.com/ubi9/ubi-micro:9.7

WORKDIR /

COPY --from=go-builder /workspace/bin/epp /app/epp

USER 65532:65532

# expose gRPC, health and metrics ports
EXPOSE 9002
EXPOSE 9003
EXPOSE 9090
# expose port for KV-Events ZMQ SUB socket
EXPOSE 5557

ENTRYPOINT ["/app/epp"]
