// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InferenceModelRewriteStatusApplyConfiguration represents a declarative configuration of the InferenceModelRewriteStatus type for use
// with apply.
//
// InferenceModelRewriteStatus defines the observed state of InferenceModelRewrite.
type InferenceModelRewriteStatusApplyConfiguration struct {
	// Conditions track the state of the InferenceModelRewrite.
	//
	// Known condition types are:
	//
	// * "Accepted"
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// InferenceModelRewriteStatusApplyConfiguration constructs a declarative configuration of the InferenceModelRewriteStatus type for use with
// apply.
func InferenceModelRewriteStatus() *InferenceModelRewriteStatusApplyConfiguration {
	return &InferenceModelRewriteStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InferenceModelRewriteStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *InferenceModelRewriteStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
