// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// InferenceObjectiveStatusApplyConfiguration represents a declarative configuration of the InferenceObjectiveStatus type for use
// with apply.
//
// InferenceObjectiveStatus defines the observed state of InferenceObjective
type InferenceObjectiveStatusApplyConfiguration struct {
	// Conditions track the state of the InferenceObjective.
	//
	// Known condition types are:
	//
	// * "Accepted"
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// InferenceObjectiveStatusApplyConfiguration constructs a declarative configuration of the InferenceObjectiveStatus type for use with
// apply.
func InferenceObjectiveStatus() *InferenceObjectiveStatusApplyConfiguration {
	return &InferenceObjectiveStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *InferenceObjectiveStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *InferenceObjectiveStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
