// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// MatchApplyConfiguration represents a declarative configuration of the Match type for use
// with apply.
//
// Match defines the criteria for matching the LLM requests.
type MatchApplyConfiguration struct {
	// Model specifies the criteria for matching the 'model' field
	// within the JSON request body.
	Model *ModelMatchApplyConfiguration `json:"model,omitempty"`
}

// MatchApplyConfiguration constructs a declarative configuration of the Match type for use with
// apply.
func Match() *MatchApplyConfiguration {
	return &MatchApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *MatchApplyConfiguration) WithModel(value *ModelMatchApplyConfiguration) *MatchApplyConfiguration {
	b.Model = value
	return b
}
