// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
)

// ModelMatchApplyConfiguration represents a declarative configuration of the ModelMatch type for use
// with apply.
//
// ModelMatch defines how to match against the model name in the request body.
type ModelMatchApplyConfiguration struct {
	// Type specifies the kind of string matching to use.
	// Supported value is "Exact". Defaults to "Exact".
	Type *apixv1alpha2.MatchValidationType `json:"type,omitempty"`
	// Value is the model name string to match against.
	Value *string `json:"value,omitempty"`
}

// ModelMatchApplyConfiguration constructs a declarative configuration of the ModelMatch type for use with
// apply.
func ModelMatch() *ModelMatchApplyConfiguration {
	return &ModelMatchApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ModelMatchApplyConfiguration) WithType(value apixv1alpha2.MatchValidationType) *ModelMatchApplyConfiguration {
	b.Type = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ModelMatchApplyConfiguration) WithValue(value string) *ModelMatchApplyConfiguration {
	b.Value = &value
	return b
}
