// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	http "net/http"

	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	scheme "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type XInferenceV1alpha2Interface interface {
	RESTClient() rest.Interface
	InferenceModelRewritesGetter
	InferenceObjectivesGetter
}

// XInferenceV1alpha2Client is used to interact with features provided by the inference.networking.x-k8s.io group.
type XInferenceV1alpha2Client struct {
	restClient rest.Interface
}

func (c *XInferenceV1alpha2Client) InferenceModelRewrites(namespace string) InferenceModelRewriteInterface {
	return newInferenceModelRewrites(c, namespace)
}

func (c *XInferenceV1alpha2Client) InferenceObjectives(namespace string) InferenceObjectiveInterface {
	return newInferenceObjectives(c, namespace)
}

// NewForConfig creates a new XInferenceV1alpha2Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*XInferenceV1alpha2Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new XInferenceV1alpha2Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*XInferenceV1alpha2Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &XInferenceV1alpha2Client{client}, nil
}

// NewForConfigOrDie creates a new XInferenceV1alpha2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *XInferenceV1alpha2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new XInferenceV1alpha2Client for the given RESTClient.
func New(c rest.Interface) *XInferenceV1alpha2Client {
	return &XInferenceV1alpha2Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apixv1alpha2.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *XInferenceV1alpha2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
