// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	applyconfigurationapixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/applyconfiguration/apix/v1alpha2"
	scheme "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferenceModelRewritesGetter has a method to return a InferenceModelRewriteInterface.
// A group's client should implement this interface.
type InferenceModelRewritesGetter interface {
	InferenceModelRewrites(namespace string) InferenceModelRewriteInterface
}

// InferenceModelRewriteInterface has methods to work with InferenceModelRewrite resources.
type InferenceModelRewriteInterface interface {
	Create(ctx context.Context, inferenceModelRewrite *apixv1alpha2.InferenceModelRewrite, opts v1.CreateOptions) (*apixv1alpha2.InferenceModelRewrite, error)
	Update(ctx context.Context, inferenceModelRewrite *apixv1alpha2.InferenceModelRewrite, opts v1.UpdateOptions) (*apixv1alpha2.InferenceModelRewrite, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferenceModelRewrite *apixv1alpha2.InferenceModelRewrite, opts v1.UpdateOptions) (*apixv1alpha2.InferenceModelRewrite, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apixv1alpha2.InferenceModelRewrite, error)
	List(ctx context.Context, opts v1.ListOptions) (*apixv1alpha2.InferenceModelRewriteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apixv1alpha2.InferenceModelRewrite, err error)
	Apply(ctx context.Context, inferenceModelRewrite *applyconfigurationapixv1alpha2.InferenceModelRewriteApplyConfiguration, opts v1.ApplyOptions) (result *apixv1alpha2.InferenceModelRewrite, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inferenceModelRewrite *applyconfigurationapixv1alpha2.InferenceModelRewriteApplyConfiguration, opts v1.ApplyOptions) (result *apixv1alpha2.InferenceModelRewrite, err error)
	InferenceModelRewriteExpansion
}

// inferenceModelRewrites implements InferenceModelRewriteInterface
type inferenceModelRewrites struct {
	*gentype.ClientWithListAndApply[*apixv1alpha2.InferenceModelRewrite, *apixv1alpha2.InferenceModelRewriteList, *applyconfigurationapixv1alpha2.InferenceModelRewriteApplyConfiguration]
}

// newInferenceModelRewrites returns a InferenceModelRewrites
func newInferenceModelRewrites(c *XInferenceV1alpha2Client, namespace string) *inferenceModelRewrites {
	return &inferenceModelRewrites{
		gentype.NewClientWithListAndApply[*apixv1alpha2.InferenceModelRewrite, *apixv1alpha2.InferenceModelRewriteList, *applyconfigurationapixv1alpha2.InferenceModelRewriteApplyConfiguration](
			"inferencemodelrewrites",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apixv1alpha2.InferenceModelRewrite { return &apixv1alpha2.InferenceModelRewrite{} },
			func() *apixv1alpha2.InferenceModelRewriteList { return &apixv1alpha2.InferenceModelRewriteList{} },
		),
	}
}
