name: Docker Build - ghcr
description: Build image using buildx
inputs:
  docker-file:
    required: true
    description: Dockerfile name
  image-name:
    required: true
    description: Image name
  tag:
    required: true
    description: Image tag
  github-token:
    required: true
    description: GitHub token for login
  registry:
    required: true
    description: Container registry (e.g., ghcr.io/llm-d)
  prerelease:
    required: true
    description: indicates whether or not this is a pre-release (not a release) build
  python-version:
    required: false
    description: Python version to use (defaults to 3.12)
    default: '3.12'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Print image info
      run: |
        echo "Image name: ${{ inputs.image-name }}"
        echo "Tag: ${{ inputs.tag }}"
        echo "Registry: ${{ inputs.registry }}"
      shell: bash

    - name: Build image and push
      run: |
        if [[ ${{ inputs.prerelease }} == "true" ]]; then
          LATEST_TAG=""
        else
          LATEST_TAG="-t ${{ inputs.registry }}/${{ inputs.image-name }}:latest"
        fi
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg PYTHON_VERSION=${{ inputs.python-version }} \
          -t ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }} \
          ${LATEST_TAG} -f ${{ inputs.docker-file }} --push .
      shell: bash
