// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/applyconfiguration/apix/v1alpha2"
	internal "github.com/llm-d/llm-d-inference-scheduler/client-go/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=inference.networking.x-k8s.io, Version=v1alpha2
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceModelRewrite"):
		return &apixv1alpha2.InferenceModelRewriteApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceModelRewriteRule"):
		return &apixv1alpha2.InferenceModelRewriteRuleApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceModelRewriteSpec"):
		return &apixv1alpha2.InferenceModelRewriteSpecApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceModelRewriteStatus"):
		return &apixv1alpha2.InferenceModelRewriteStatusApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceObjective"):
		return &apixv1alpha2.InferenceObjectiveApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceObjectiveSpec"):
		return &apixv1alpha2.InferenceObjectiveSpecApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("InferenceObjectiveStatus"):
		return &apixv1alpha2.InferenceObjectiveStatusApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("Match"):
		return &apixv1alpha2.MatchApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("ModelMatch"):
		return &apixv1alpha2.ModelMatchApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("PoolObjectReference"):
		return &apixv1alpha2.PoolObjectReferenceApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("TargetModel"):
		return &apixv1alpha2.TargetModelApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
