// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/applyconfiguration/apix/v1alpha2"
	typedapixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned/typed/apix/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeInferenceModelRewrites implements InferenceModelRewriteInterface
type fakeInferenceModelRewrites struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.InferenceModelRewrite, *v1alpha2.InferenceModelRewriteList, *apixv1alpha2.InferenceModelRewriteApplyConfiguration]
	Fake *FakeXInferenceV1alpha2
}

func newFakeInferenceModelRewrites(fake *FakeXInferenceV1alpha2, namespace string) typedapixv1alpha2.InferenceModelRewriteInterface {
	return &fakeInferenceModelRewrites{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.InferenceModelRewrite, *v1alpha2.InferenceModelRewriteList, *apixv1alpha2.InferenceModelRewriteApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("inferencemodelrewrites"),
			v1alpha2.SchemeGroupVersion.WithKind("InferenceModelRewrite"),
			func() *v1alpha2.InferenceModelRewrite { return &v1alpha2.InferenceModelRewrite{} },
			func() *v1alpha2.InferenceModelRewriteList { return &v1alpha2.InferenceModelRewriteList{} },
			func(dst, src *v1alpha2.InferenceModelRewriteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.InferenceModelRewriteList) []*v1alpha2.InferenceModelRewrite {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.InferenceModelRewriteList, items []*v1alpha2.InferenceModelRewrite) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
