// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/llm-d/llm-d-inference-scheduler/apix/v1alpha2"
	apixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/applyconfiguration/apix/v1alpha2"
	typedapixv1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned/typed/apix/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeInferenceObjectives implements InferenceObjectiveInterface
type fakeInferenceObjectives struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.InferenceObjective, *v1alpha2.InferenceObjectiveList, *apixv1alpha2.InferenceObjectiveApplyConfiguration]
	Fake *FakeXInferenceV1alpha2
}

func newFakeInferenceObjectives(fake *FakeXInferenceV1alpha2, namespace string) typedapixv1alpha2.InferenceObjectiveInterface {
	return &fakeInferenceObjectives{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.InferenceObjective, *v1alpha2.InferenceObjectiveList, *apixv1alpha2.InferenceObjectiveApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("inferenceobjectives"),
			v1alpha2.SchemeGroupVersion.WithKind("InferenceObjective"),
			func() *v1alpha2.InferenceObjective { return &v1alpha2.InferenceObjective{} },
			func() *v1alpha2.InferenceObjectiveList { return &v1alpha2.InferenceObjectiveList{} },
			func(dst, src *v1alpha2.InferenceObjectiveList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.InferenceObjectiveList) []*v1alpha2.InferenceObjective {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.InferenceObjectiveList, items []*v1alpha2.InferenceObjective) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
