// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/llm-d/llm-d-inference-scheduler/client-go/clientset/versioned/typed/apix/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeXInferenceV1alpha2 struct {
	*testing.Fake
}

func (c *FakeXInferenceV1alpha2) InferenceModelRewrites(namespace string) v1alpha2.InferenceModelRewriteInterface {
	return newFakeInferenceModelRewrites(c, namespace)
}

func (c *FakeXInferenceV1alpha2) InferenceObjectives(namespace string) v1alpha2.InferenceObjectiveInterface {
	return newFakeInferenceObjectives(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeXInferenceV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
